# Managed Manifest
# File: platform/gitops/apps/ocipi-viewer.yaml
# Purpose: Argo CD child application defining sync source and destination for a platform component.
# Owner: integration-hub platform team

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocipi-viewer-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/wrenkredhat2/integration-hub-service-gitops.git
    targetRevision: main
    path: platform/apps/ocipi-viewer/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: ocipi-viewer-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
