apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orl-dpro-int-iam

resources:
  - rolebinding.yaml
  - ../../../base/keycloak
  - platform-dev-realm-import.yaml

patches:

  - target:
      kind: Keycloak
      name: orlen-int-kc
    patch: |-
      - op: replace
        path: /spec/hostname/hostname
        value: "keycloak.apps.dev.orlen.pl"
      - op: add
        path: /spec/truststores
        value:
          openshift-trusted-ca:
            configMap:
              name: trusted-ca
  - target:
      kind: Secret
      name: keycloak-bootstrap-admin
    patch: |-
      - op: replace
        path: /stringData/password
        value: "dev-orlen-2026"
