kind: Secret
apiVersion: v1
metadata:
  name: kafka-nbp-runtime
  namespace: orl-dpro-int-flows
stringData:

  KAFKA_BOOTSTRAP_SERVERS: orl-clust-kafka-bootstrap.orl-dpro-int-streams.svc.cluster.local:9092

  #KEYCLOAK_URL: yyyy
  #KEYCLOAK_CLIENT_ID: aaaa
  #KEYCLOAK_CLIENT_SECRET: yyyy
  
  OCIPI_DB_URL: jdbc:sqlserver://SPKNWSP19T02.orlen.pl:1433;DatabaseName=EDIDOCUM_TEST;encrypt=true;trustServerCertificate=true;applicationName=OAF
  OCIPI_DB_USER: pi_interface
  OCIPI_DB_PASS: p3GGRBvMj86szvWt
  OCIPI_DB_TYPE: mssql

  STATUS_DB_URL: jdbc:postgresql://postgres-status/status-db
  STATUS_DB_USER: status
  STATUS_DB_PASS: supersecret

  # ---------- EHURT OAuth + REST ----------
  EHURT_TOKEN_URL: https://borlehurtt04/domainIdentity/AuthDomain/
  EHURT_CLIENT_ID: FE3608B26C674F6E9F123A94B8B99081
  EHURT_CLIENT_SECRET: ehurt-secret
  EHURT_GRANT_TYPE: client_credentials

  EHURT_BASIC_USERNAME: sseHurtAdminTST
  EHURT_BASIC_PASSWORD: (d5Ae]w_QxX/tJ
  EHURT_BASIC_DOMAIN: ORLEN
  EHURT_REST_URL: https://borlehurtt04/common/UpdateExchangeRate

  # ---------- D7I SOAP + Basic Auth ----------

  D7I_SOAP_URL: https://d7itestintegracja.orlen.pl/api/v1/connector/engine/operation/inbound/in_ExchangeRates
  D7I_BASIC_USER: WS_TEST
  D7I_BASIC_PASS: 1mYMTfJfDmYAt8hniRWt
  D7I_SOAP_TEMPLATE: NotUsed

  # ---------- NBP ACCESS Baic Auth through Proxy ----------

  NBP_BASIC_USERNAME: ssRHAFArgo
  NBP_BASIC_PASSWORD: U$q^er{O0%RwA6WMvl
  NBP_BASIC_DOMAIN: ORLEN
  NBP_REQUEST_URL: https://api.nbp.pl/api/exchangerates/tables/A?bridgeEndpoint=true&format=json&proxyHost=192.168.20.10&proxyPort=9090&proxyAuthUsername=ORLEN\\ssRHAFArgo&proxyAuthPassword=U$q^er{O0%RwA6WMvl
  NBP_REQUEST_URL_1: http://api.nbp.pl/api/exchangerates/tables/A?bridgeEndpoint=true&format=json

type: Opaque