apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: orl-clust
  namespace: kafka-streams
spec:
  kafka:
    # ...
    listeners:
      # ...
      - name: listener1
        port: 9094
        type: route
        tls: true
        configuration:
          bootstrap:
            host: orl-clust-kafka-listener1-bootstrap-kafka-streams.apps.dev.orlen.pl
      # --- NEW IINTERNAL LISTENER ---
      - name: internal
        port: 9092
        type: internal
        tls: false
    template:
      pod:
        volumes:
          - name: trusted-ca-bundle
            configMap:
              name: trusted-ca
      kafkaContainer:
        env:
          - name: SSL_CERT_FILE
            value: /mnt/trusted-ca/ca-bundle.crt
        volumeMounts:
          - name: trusted-ca-bundle
            mountPath: /mnt/trusted-ca
            readOnly: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        volumes:
          - name: trusted-ca-bundle
            configMap:
              name: trusted-ca
      topicOperatorContainer:
        env:
          - name: SSL_CERT_FILE
            value: /mnt/trusted-ca/ca-bundle.crt
        volumeMounts:
          - name: trusted-ca-bundle
            mountPath: /mnt/trusted-ca
            readOnly: true
      userOperatorContainer:
        env:
          - name: SSL_CERT_FILE
            value: /mnt/trusted-ca/ca-bundle.crt
        volumeMounts:
          - name: trusted-ca-bundle
            mountPath: /mnt/trusted-ca
            readOnly: true
