apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Ressourcen, die verwaltet werden sollen
resources:
  - node-pool.yaml
  - kafka-cluster.yaml
  - kafka-console-client-secret.yaml
  - kafka-console.yaml
  - nbp-data-topic.yaml

# 2. Gemeinsame Metadaten für alle Ressourcen
namespace: kafka