apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: orl-clust-pl
  namespace: kafka-streams
  labels:
    strimzi.io/cluster: orl-clust # Must match the name of your Kafka CR
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false