kind: Secret
apiVersion: v1
metadata:
  name: kafka-nbp-runtime
  namespace: orl-dpro-int-flows
stringData:
  KAFKA_BOOTSTRAP_SERVERS: xxxxx
  KEYCLOAK_URL: yyyy
  KEYCLOAK_CLIENT_ID: aaaa
  KEYCLOAK_CLIENT_SECRET: yyyy
  OCIPI_DB_URL: yyyy
  OCIPI_DB_USER: yyyy
  OCIPI_DB_PASS: yyyy
  STATUS_DB_URL: yyyy
  STATUS_DB_USER: yyyy
  STATUS_DB_PASS: yyyy
  EHURT_TOKEN_URL: yyyy
  EHURT_CLIENT_ID: yyyy
  EHURT_CLIENT_SECRET: yyyy
  EHURT_REST_URL: yyyy
type: Opaque