kind: Secret
apiVersion: v1
metadata:
  name: kafka-nbp-runtime
  namespace: orl-dpro-int-flows
stringData:
  KAFKA_BOOTSTRAP_SERVERS: xxxxx
  KEYCLOAK_URL: yyyy
  KEYCLOAK_CLIENT_ID: aaaa
  KEYCLOAK_CLIENT_SECRET: yyyy
  OCIPI_DB_URL: jdbc:sqlserver://SPKNWSP19T02.orlen.pl:1433;DatabaseName=EDIDOCUM_TEST;encrypt=true;trustServerCertificate=true;applicationName=OAF
  OCIPI_DB_USER: pi_interface
  OCIPI_DB_PASS: p3GGRBvMj86szvWt
  OCIPI_DB_TYPE: mssql
  STATUS_DB_URL: yyyy
  STATUS_DB_USER: yyyy
  STATUS_DB_PASS: yyyy
  EHURT_TOKEN_URL: yyyy
  EHURT_CLIENT_ID: yyyy
  EHURT_CLIENT_SECRET: yyyy
  EHURT_REST_URL: yyyy
type: Opaque