# -----------------------------
# Secret (credentials)
# -----------------------------
apiVersion: v1
kind: Secret
metadata:
  name: postgres-status-secret
  annotations:
    argocd.argoproj.io/sync-wave: "00"
type: Opaque

stringData:
  POSTGRESQL_DATABASE: status-db
  POSTGRESQL_USER: status
  POSTGRESQL_PASSWORD: supersecret
  POSTGRESQL_ADMIN_PASSWORD: adminpass