apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orl-dpro-int-api

resources:
  - rolebinding.yaml
  - ../../../base/trusted-ca
  - ../../../base/3scale

#namePrefix: prod-
#commonLabels:
#  env: production

# Mehr Power für Prod
patches:

  - target:
      kind: APIManager
      name: orlen-apimanager
    patch: |-
      - op: replace
        path: /spec/wildcardDomain
        value: apps.dev.orlen.pl
      - op: replace
        path: /spec/system/fileStorage/persistentVolumeClaim/storageClassName
        value: ocs-external-storagecluster-cephfs

  - target:
      kind: Secret
      name: backend-redis
    patch: |-
      - op: replace
        path: /stringData/REDIS_STORAGE_URL
        value: redis://valkey.orl-dpro-int-api.svc.cluster.local:6379/0
      - op: replace
        path: /stringData/REDIS_QUEUES_URL
        value: redis://valkey.orl-dpro-int-api.svc.cluster.local:6379/1

  - target:
      kind: Secret
      name: system-redis
    patch: |-
      - op: replace
        path: /stringData/URL
        value:   redis://valkey.orl-dpro-int-api.svc.cluster.local:6379/2

  - target:
      kind: Secret
      name: system-database
    patch: |-
      - op: replace
        path: /stringData/URL
        value:   postgresql://3scale:supersecret@postgres.orl-dpro-int-api.svc.cluster.local:5432/3scale-db

  - target:
      kind: Secret
      name: keycloak-sso
    patch: |-
      - op: replace
        path: /stringData/clientSecret
        value: jJKkcwO1B2yyEtVbN1kpqFgxUT92O5xO
      - op: replace
        path: /stringData/issuer
        value: https://keycloak.apps.dev.orlen.pl/realms/platform-dev
  - target:
      kind: Job
      name: configure-3scale-sso
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/1/value
        value: apps.dev.orlen.pl

# Festgelegtes Image für Stabilität
#images:
#  - name: my-app-image
#    newName: registry.example.com/app
#    newTag: "2.4.0-stable"