apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Ressourcen, die verwaltet werden sollen
resources:
  - backend-redis-secret.yaml
  - system-redis-secret.yaml
  - system-database-secret.yaml
  - api-manager.yaml
  - keycloak-sso.yaml
  - configure-3scale-sso.yaml
  - configure-3scale-ca-injection.yaml

# 2. Gemeinsame Metadaten für alle Ressourcen
namespace: 3scale
