apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orders-api
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://git.svc.arencloud.com/egevorky/rhdemo.git
    targetRevision: HEAD
    path: apps/team-a/overlays/dev
  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false