apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - rolebinding.yaml
  - ../../../base/keycloak
  - platform-prod-realm-import.yaml

patches:

  - target:
      kind: Keycloak
      name: orlen-int-kc
    patch: |-
      - op: replace
        path: /spec/hostname/hostname
        value: "rhbk-prod.apps.cl01.arencloud.com"
      - op: add
        path: /spec/truststores
        value:
          openshift-trusted-ca:
            configMap:
              name: trusted-ca
  - target:
      kind: Secret
      name: keycloak-bootstrap-admin
    patch: |-
      - op: replace
        path: /stringData/password
        value: "prod-orlen-2026"
