apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Ressourcen, die verwaltet werden sollen
resources:
  - keycloak-db-secret.yaml
  - keycloak-bootstrap-admin.yaml
  - keycloak-instance.yaml

# 2. Gemeinsame Metadaten für alle Ressourcen
namespace: keykloak