apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orl-dpro-int-streams

resources:
  - rolebinding.yaml
  - ../../../base/kafka-streams

patches:

  - target:
      kind: Kafka
      name: orl-clust
    patch: |-
      - op: replace
        path: /spec/kafka/listeners/0/configuration/bootstrap/host
        value: "orl-clust-kafka-listener1-bootstrap-kafka-streams.apps.cl01.arencloud.com"
      - op: add
        path: /spec/kafka/config
        value:
          default.replication.factor: 3
          min.insync.replicas: 2
      - op: add
        path: /spec/kafka/template/pod/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                strimzi.io/cluster: orl-clust
                strimzi.io/name: orl-clust-kafka
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                strimzi.io/cluster: orl-clust
                strimzi.io/name: orl-clust-kafka
      - op: add
        path: /spec/kafka/template/kafkaContainer/resources
        value:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
      - op: add
        path: /spec/entityOperator/template/pod/topologySpreadConstraints
        value:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                strimzi.io/cluster: orl-clust
                strimzi.io/name: orl-clust-entity-operator
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                strimzi.io/cluster: orl-clust
                strimzi.io/name: orl-clust-entity-operator
      - op: add
        path: /spec/entityOperator/template/topicOperatorContainer/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      - op: add
        path: /spec/entityOperator/template/userOperatorContainer/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

  - target:
      kind: KafkaNodePool
      name: orl-clust-pl
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/resources
        value:
          requests:
            cpu: "1"
            memory: 2Gi
          limits:
            cpu: "2"
            memory: 4Gi
      - op: add
        path: /spec/template
        value:
          pod:
            topologySpreadConstraints:
              - maxSkew: 1
                topologyKey: topology.kubernetes.io/zone
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    strimzi.io/cluster: orl-clust
                    strimzi.io/name: orl-clust-kafka
              - maxSkew: 1
                topologyKey: kubernetes.io/hostname
                whenUnsatisfiable: DoNotSchedule
                labelSelector:
                  matchLabels:
                    strimzi.io/cluster: orl-clust
                    strimzi.io/name: orl-clust-kafka

  - target:
      kind: Console
      name: orl-clust-console
    patch: |-
      - op: replace
        path: /spec/hostname
        value: kafka-console.apps.cl01.arencloud.com
      - op: replace
        path: /spec/security/oidc/authServerUrl
        value: "https://rhbk-dev.apps.cl01.arencloud.com/realms/platform-dev"
      - op: replace
        path: /spec/security/oidc/clientId
        value: "kafka-console"
      - op: add
        path: /spec/security/oidc/trustStore
        value:
          type: PEM
          content:
            valueFrom:
              configMapKeyRef:
                name: trusted-ca
                key: ca-bundle.crt

  - target:
      kind: Secret
      name: orlen-kafka-console-oidc
    patch: |-
      - op: replace
        path: /stringData/client-secret
        value: l3Hk6TnbBV2oGoBd3bC2xCnC9lFV1bt0
