apiVersion: capabilities.3scale.net/v1beta1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: orders-ui
spec:
  accountCR:
    name: team-a
  applicationPlanName: basic
  productCR:
    name: orders-api
  name: orders-ui
  description: Orders UI application