apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperUser
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: alice
spec:
  username: alice
  email: alice@example.com
  role: admin
  passwordCredentialsRef:
    name: alice-password
  developerAccountRef:
    name: team-a
  providerAccountRef:
    name: mytenant