apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: keycloak-issuer
type: Opaque
stringData:
  issuerEndpoint: "https://zync-dev:REPLACE_ME_ZYNC_CLIENT_SECRET@rhbk-dev.apps.cl01.arencloud.com/realms/platform-dev"