apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - trusted-ca-configmap.yaml
  - deployment.yaml
  - service.yaml
  - keycloak-issuer-secret.yaml
  - application-orders-ui.yaml
  - backend-orders.yaml
  - backend-proxy-secret.yaml
  - developer-account.yaml
  - developer-user-secret.yaml
  - developer-user.yaml
  - product-orders.yaml
  - provider-account-secret.yaml
