apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: mytenant
type: Opaque
stringData:
  adminURL: https://3scale-admin.apps.cl01.arencloud.com
  token: REPLACE_ME_3SCALE_ACCESS_TOKEN