apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-camel
spec:
  template:
    spec:
      containers:
        - name: team-a-camel
          env:
            - name: ENVIRONMENT
              value: stage
          image: image-registry.openshift-image-registry.svc:5000/platform-ci/team-a-camel:stage
