apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: valkey-ha
  annotations:
    argocd.argoproj.io/sync-wave: "00"
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: valkey-ha
